"""
app.py
-------
Streamlit front-end for the Digital Matchmaker.

DESIGN RULE: this file contains ZERO recommendation logic of its own.
It only imports and calls the already-tested TechStackRecommender
pipeline (pipeline.py / data_ingestion.py / feature_extractor.py /
recommendation_engine.py). Every match shown here is produced by the
exact same TF-IDF + Cosine Similarity math validated end-to-end in
main.py -- this is a presentation layer, not a second implementation.

Run:
    streamlit run app.py
"""

import html
from pathlib import Path

import streamlit as st

from pipeline import TechStackRecommender

# Resolve raw_skills.csv relative to THIS file's location, never to the
# process's current working directory. Locally, "streamlit run app.py"
# from inside this folder happens to make those the same thing -- but
# Streamlit Community Cloud mounts the repo and runs from the repo root,
# not from this subfolder, so a bare relative path silently breaks there.
APP_DIR = Path(__file__).resolve().parent
DATASET_PATH = APP_DIR / "raw_skills.csv"

st.set_page_config(
    page_title="The Digital Matchmaker — DecodeLabs Project 3",
    page_icon="🎯",
    layout="centered",
)

# ---------------------------------------------------------------------
# One-time setup: load items + fit the shared TF-IDF vocabulary.
# Cached so re-running this script on every widget interaction
# (Streamlit's normal execution model) doesn't refit the vectorizer
# on every keystroke.
# ---------------------------------------------------------------------
@st.cache_resource
def load_engine() -> TechStackRecommender:
    engine = TechStackRecommender(str(DATASET_PATH))
    engine.load()
    return engine


engine = load_engine()
suggested_skills = engine.ingestion.get_suggested_skills(top_k=8)

# ---------------------------------------------------------------------
# Styling -- pulled from the same indigo (#6366F1) already used as this
# repo's brand color in the root README badges, not a generic Streamlit
# default theme. Only custom markup generated by this file is styled
# here; no reliance on Streamlit's internal/unstable CSS class names.
# ---------------------------------------------------------------------
st.markdown(
    """
    <style>
    .match-card {
        display: flex; align-items: center; gap: 18px;
        background: #FFFFFF; border: 1px solid #E7E5F5;
        border-radius: 16px; padding: 18px 22px; margin-bottom: 14px;
        box-shadow: 0 2px 10px rgba(99, 102, 241, 0.08);
        animation: fadeIn 0.35s ease-in-out;
    }
    .match-rank { font-size: 12px; font-weight: 700; color: #8B5CF6;
        letter-spacing: 0.08em; text-transform: uppercase; }
    .match-title { font-size: 17px; font-weight: 700; color: #1E1B4B; margin: 2px 0 6px; }
    .match-desc { font-size: 13px; color: #6B7280; line-height: 1.4; }
    .pill { display: inline-block; font-size: 11px; font-weight: 700;
        padding: 3px 10px; border-radius: 999px; margin-bottom: 6px; }
    .pill-platform { background: #FEF3C7; color: #92400E; }
    .pill-tool { background: #DBEAFE; color: #1E40AF; }
    .pill-jobrole { background: #EDE9FE; color: #5B21B6; }
    .ring-outer { width: 70px; height: 70px; border-radius: 50%;
        display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    .ring-inner { width: 52px; height: 52px; border-radius: 50%; background: #FFFFFF;
        display: flex; align-items: center; justify-content: center;
        font-weight: 700; font-size: 13px; color: #1E1B4B; }
    .coldstart-banner { background: #EEF2FF; border: 1px solid #C7D2FE;
        border-radius: 12px; padding: 14px 18px; margin-bottom: 18px;
        font-size: 14px; color: #312E81; line-height: 1.5; }
    @keyframes fadeIn {
        from { opacity: 0; transform: translateY(6px); }
        to   { opacity: 1; transform: translateY(0); }
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------
st.markdown("## 🎯 The Digital Matchmaker")
st.markdown(
    "Tell it what you know, it tells you what to learn next — matched by "
    "**TF-IDF + Cosine Similarity**, not guesswork. *(DecodeLabs Project 3)*"
)

with st.sidebar:
    st.markdown("### How this works")
    st.markdown(
        "This is a **Content-Based Filtering** engine. Every skill you add "
        "is vectorized with TF-IDF into the same feature space as the item "
        "dataset, then ranked by **Cosine Similarity** — the angle between "
        "your skill vector and each item's, not raw distance."
    )
    st.markdown(
        "Fewer than 3 skills, or skills with zero overlap with the "
        "dataset, and the **cold-start guard** kicks in automatically — "
        "you'll never see an empty result."
    )
    st.divider()
    st.markdown(
        "[View source on GitHub](https://github.com/mahaveer-mkj/"
        "DecodeLabs-Internship/tree/main/Project-3-Recommendation-Engine)"
    )

st.divider()

# ---------------------------------------------------------------------
# Input
# ---------------------------------------------------------------------
st.markdown("#### Your skills & interests")

picked = st.multiselect(
    "Pick from skills known to this dataset",
    options=sorted(set(suggested_skills + [
        "python", "javascript", "kubernetes", "docker",
        "machine learning", "sql", "react", "security",
    ])),
    default=[],
    help="These are guaranteed to have at least some overlap with the item vocabulary.",
)

custom_raw = st.text_input(
    "Or type your own (comma-separated)",
    placeholder="e.g. Rust, Terraform, GraphQL",
)
custom = [s.strip() for s in custom_raw.split(",") if s.strip()]

all_skills = list(dict.fromkeys(picked + custom))  # de-dup, preserve order

weights = {}
if all_skills:
    st.markdown("#### How much do you care about each one?")
    st.caption("1 = casual interest · 5 = core strength")
    cols = st.columns(min(len(all_skills), 3))
    for i, skill in enumerate(all_skills):
        with cols[i % len(cols)]:
            weights[skill] = st.slider(skill.title(), 1, 5, 3, key=f"w_{skill}")

st.divider()

# ---------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------
if not all_skills:
    st.info(
        f"👋 Add a few skills above to get matched. Popular ones in this "
        f"dataset: **{', '.join(suggested_skills[:5])}**."
    )
else:
    # The ONLY recommendation call in this entire file. Same pipeline,
    # same math, same code path as main.py.
    results = engine.recommend(all_skills, weights)
    profile = engine.last_profile

    if profile is not None and profile.is_cold_start:
        safe_skills = html.escape(", ".join(profile.skills))
        st.markdown(
            f"""<div class="coldstart-banner">
            ❄️ <strong>Cold-start guard activated</strong> — your input
            didn't clear the bar (too few skills, or zero overlap with the
            dataset), so trending skills from the dataset were blended in
            automatically: <strong>{safe_skills}</strong>. This is the same
            safety net documented in the README — you're never shown an
            empty result.
            </div>""",
            unsafe_allow_html=True,
        )

    st.markdown("#### Your Top 3 Matches")

    pill_class = {"Platform": "pill-platform", "Tool": "pill-tool", "JobRole": "pill-jobrole"}

    for rank, match in enumerate(results, start=1):
        pct = max(0, min(100, round(match.similarity_score * 100)))
        pill = pill_class.get(match.category, "pill-tool")
        title = html.escape(match.item_name)
        desc = html.escape(match.description)
        category = html.escape(match.category)

        st.markdown(
            f"""
            <div class="match-card">
                <div class="ring-outer" style="background: conic-gradient(#6366F1 {pct}%, #E5E7EB 0);">
                    <div class="ring-inner">{match.similarity_score}</div>
                </div>
                <div>
                    <div class="match-rank">#{rank} Match</div>
                    <div><span class="pill {pill}">{category}</span></div>
                    <div class="match-title">{title}</div>
                    <div class="match-desc">{desc}</div>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.caption(
        "The number inside each ring is the raw Cosine Similarity score "
        "(0–1 scale) — not a 'compatibility percentage'. The ring's fill "
        "is just that same number drawn visually, nothing rescaled or "
        "exaggerated."
    )
